name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache Cargo Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-bin-typos-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-bin-typos-${{ runner.os }}-
      - name: Install typos
        run: |
          if ! command -v typos &> /dev/null; then
            cargo install typos-cli
          fi
      - name: Generate Changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          args: -vv --latest --no-exec --github-repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    name: Create GitHub Release
    needs: generate-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "${{ needs.generate-changelog.outputs.release_body }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
