name: Continuous Integration

on:
  push:
    branches:
      - '**'  
    tags-ignore:
      - '**' 

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go from go.mod
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Check Conventional Commits
      uses: webiny/action-conventional-commits@v1.3.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-mod-${{ runner.os }}-

    - name: Tidy Go modules
      run: go mod tidy

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.0

    - name: Run tests with make
      run: make test
